name = "ClusterEnsembles"
uuid = "e493a4bf-88d6-40ad-84dc-847a9b000e38"
license = "MIT"
authors = ["Takehiro Sano <sano@momo.cs.okayama-u.ac.jp>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"

[compat]
LightGraphs = "1.3.5"
Metis = "0.1.0, 1.0.0"
Clustering = "0.14.2"
julia = "1.3, 1.4, 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
